
//
// IsProcFeatPresent.c - enumerate OS CPU feature flags
//

#include <windows.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#define MAX_FEATURE (200)

#define FEATURE(x) [ x ] = # x

const char *FeatureStrings[MAX_FEATURE] =
{
    // from winnt.h as of SDK 26100 24H2 GE_RELEASE

    FEATURE(PF_FLOATING_POINT_PRECISION_ERRATA),
    FEATURE(PF_FLOATING_POINT_EMULATED),
    FEATURE(PF_COMPARE_EXCHANGE_DOUBLE),
    FEATURE(PF_MMX_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_PPC_MOVEMEM_64BIT_OK),
    FEATURE(PF_ALPHA_BYTE_INSTRUCTIONS),
    FEATURE(PF_XMMI_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_3DNOW_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_RDTSC_INSTRUCTION_AVAILABLE),
    FEATURE(PF_PAE_ENABLED),
    FEATURE(PF_XMMI64_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_SSE_DAZ_MODE_AVAILABLE),
    FEATURE(PF_NX_ENABLED),
    FEATURE(PF_SSE3_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_COMPARE_EXCHANGE128),
    FEATURE(PF_COMPARE64_EXCHANGE128),
    FEATURE(PF_CHANNELS_ENABLED),
    FEATURE(PF_XSAVE_ENABLED),
    FEATURE(PF_ARM_VFP_32_REGISTERS_AVAILABLE),
    FEATURE(PF_ARM_NEON_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_SECOND_LEVEL_ADDRESS_TRANSLATION),
    FEATURE(PF_VIRT_FIRMWARE_ENABLED),
    FEATURE(PF_RDWRFSGSBASE_AVAILABLE),
    FEATURE(PF_FASTFAIL_AVAILABLE),
    FEATURE(PF_ARM_DIVIDE_INSTRUCTION_AVAILABLE),
    FEATURE(PF_ARM_64BIT_LOADSTORE_ATOMIC),
    FEATURE(PF_ARM_EXTERNAL_CACHE_AVAILABLE),
    FEATURE(PF_ARM_FMAC_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_RDRAND_INSTRUCTION_AVAILABLE),
    FEATURE(PF_ARM_V8_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_V8_CRYPTO_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_V8_CRC32_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_RDTSCP_INSTRUCTION_AVAILABLE),
    FEATURE(PF_RDPID_INSTRUCTION_AVAILABLE),
    FEATURE(PF_ARM_V81_ATOMIC_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_MONITORX_INSTRUCTION_AVAILABLE),
    FEATURE(PF_SSSE3_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_SSE4_1_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_SSE4_2_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_AVX_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_AVX2_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_AVX512F_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ERMS_AVAILABLE),
    FEATURE(PF_ARM_V82_DP_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_V83_JSCVT_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_V83_LRCPC_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE2_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE2_1_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_AES_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_PMULL128_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_BITPERM_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_BF16_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_EBF16_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_B16B16_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_SHA3_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_SM4_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_I8MM_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_F32MM_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SVE_F64MM_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_BMI2_INSTRUCTIONS_AVAILABLE),

    // added in SDK 26100.4188 refresh (VS2022 17.4.8 July 2025)

    FEATURE(PF_MOVDIR64B_INSTRUCTION_AVAILABLE),
    FEATURE(PF_ARM_LSE2_AVAILABLE),
    FEATURE(PF_RESERVED_FEATURE),
    FEATURE(PF_ARM_SHA3_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SHA512_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_V82_I8MM_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_V82_FP16_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_V86_BF16_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_V86_EBF16_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME2_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME2_1_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME2_2_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_AES_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_SBITPERM_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_SF8MM4_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_SF8MM8_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_SF8DP2_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_SF8DP4_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_SF8FMA_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_F8F32_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_F8F16_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_F16F16_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_B16B16_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_F64F64_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_I16I64_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_LUTv2_INSTRUCTIONS_AVAILABLE),
    FEATURE(PF_ARM_SME_FA64_INSTRUCTIONS_AVAILABLE),

};

int __cdecl main()
{
    for (unsigned Feature = 0; Feature < MAX_FEATURE; Feature++)
    {
        if (IsProcessorFeaturePresent(Feature) != FALSE)
        {
            printf("feature %02u present: %s\n", Feature,
                  FeatureStrings[Feature] ? FeatureStrings[Feature] : "" );
        }
    }
}

